# Star Cluster Catalog Analysis with Pandas

- PPMXL ----------------------------------> star/source ID
  
- RAJ2000[deg] ---------------------------> Right Ascension in degrees
  
- DEJ2000[deg] ---------------------------> Declination in degrees
  
- pmRA[mas/yr] --------------------------> proper motion in RA
  
- pmDE[mas/yr] --------------------------> proper motion in De
  
- e_pmRA[mas/yr] -----------------------> error in proper motion RA
  
- e_pmDE[mas/yr] -----------------------> error in proper motion Dec
  
- Jmag[mag] -------------------------------> J-band infrared magnitude
  
- e_Jmag[mag] ----------------------------> error in J magnitude
  
- Kmag[mag] ------------------------------> K-band infrared magnitude
  
- e_Kmag[mag] ---------------------------> error in K magnitude

In [26]:
import pandas as pd
import numpy as np

* The original .xlsx file is around 65 MB. Run the code below to read .csv file and get rid of all metadata and other unnecessary data in original .xlsx file:

In [27]:
df= pd.read_csv('vizier_votable_catalog.csv') # Enter /data/sample.csv if you want to use the sample dataset instead of the full one.

Just to take a grasp of dataset:

In [28]:
display(df.head())

,PPMXL,RAJ2000[deg],DEJ2000[deg],pmRA[mas/yr],pmDE[mas/yr],e_pmRA[mas/yr],e_pmDE[mas/yr],Jmag[mag],e_Jmag[mag],Kmag[mag],e_Kmag[mag]
0,407349000000000000,45.959256,49.962081,17.6,1.9,6.3,6.3,16.713,0.146,15.928,NaN
1,407352000000000000,45.959337,49.891708,-5.3,0.6,5.5,5.5,,,,NaN
2,407349000000000000,45.959650,49.898794,-2.9,0.7,4.8,4.8,16.899,0.167,15.7,0.196
3,407350000000000000,45.959841,49.992809,0.4,2.9,5.5,5.5,,,,NaN
4,407349000000000000,45.960393,49.909459,-4.9,4.0,4.8,4.8,16.7,0.129,15.693,0.201

And to have more information about our dataset:

In [29]:
display(df.describe())
display(df.info())

,PPMXL,RAJ2000[deg],DEJ2000[deg],pmRA[mas/yr],pmDE[mas/yr],e_pmRA[mas/yr],e_pmDE[mas/yr],e_Kmag[mag]
count,9.363290e+05,936329.000000,936329.000000,936329.000000,936329.000000,936329.000000,936329.000000,451341.000000
mean,4.385381e+17,51.163103,49.860171,-2.302923,-3.426207,6.021949,6.023579,0.111040
std,4.349696e+16,2.515901,1.641183,56.174083,74.676329,2.503662,2.504908,0.075859
min,4.069950e+17,45.958814,46.561318,-8283.200000,-7681.700000,0.200000,0.200000,0.000000
25%,4.105920e+17,49.173383,48.526469,-5.000000,-7.300000,4.300000,4.300000,0.050000
50%,4.127500e+17,51.139387,49.852997,-1.000000,-2.500000,5.600000,5.600000,0.102000
75%,5.058270e+17,53.180827,51.211242,3.400000,1.600000,7.200000,7.200000,0.163000
max,5.106180e+17,56.203615,53.160317,7784.300000,8136.700000,50.000000,50.000000,9.998000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 936329 entries, 0 to 936328
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PPMXL           936329 non-null  int64
 1   RAJ2000[deg]    936329 non-null  float64
 2   DEJ2000[deg]    936329 non-null  float64
 3   pmRA[mas/yr]    936329 non-null  float64
 4   pmDE[mas/yr]    936329 non-null  float64
 5   e_pmRA[mas/yr]  936329 non-null  float64
 6   e_pmDE[mas/yr]  936329 non-null  float64
 7   Jmag[mag]       936329 non-null  object
 8   e_Jmag[mag]     936329 non-null  object
 9   Kmag[mag]       936329 non-null  object
 10  e_Kmag[mag]     451341 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 78.6+ MB

None

We have around 9 hundred thousand stars, in total 19 million information distributed in 11 columns :

In [30]:
display(df.size)
display(df.shape)

10299619

(936329, 11)

## Drop NaN
First of all, let's see how many NaN values we have among all elements and then drop them. 
    - first count the NaN

In [31]:
display(df.sample(10))
display(df.isnull().sum())

,PPMXL,RAJ2000[deg],DEJ2000[deg],pmRA[mas/yr],pmDE[mas/yr],e_pmRA[mas/yr],e_pmDE[mas/yr],Jmag[mag],e_Jmag[mag],Kmag[mag],e_Kmag[mag]
743253,413738000000000000,53.922403,47.556738,5.3,-10.1,4.4,4.4,15.616,0.066,15.061,0.120
51049,410533000000000000,47.410271,49.563620,-0.2,-5.8,5.5,5.5,,,,NaN
813983,409335000000000000,48.219147,52.250316,10.6,-2.0,6.6,6.6,17.004,0.182,15.96,0.243
105382,412225000000000000,49.123197,50.196725,2.6,-2.6,8.1,8.1,,,,NaN
664510,413329000000000000,52.088579,47.942387,-4.2,-3.4,5.9,5.9,,,,NaN
918105,506186000000000000,51.734781,52.979914,7.0,-4.8,4.0,4.0,13.943,0.027,13.394,0.039
31685,413174000000000000,53.189421,49.866568,8.0,-19.0,7.8,7.8,,,,NaN
158079,412520000000000000,50.636096,49.331526,4.7,-11.4,4.1,4.1,12.82,0.022,12.165,0.024
932004,505752000000000000,50.481330,53.072720,-4.0,-1.2,4.7,4.7,16.45,0.109,15.465,0.168
680674,408912000000000000,47.280173,51.917564,-3.1,-1.4,4.6,4.6,16.387,0.104,15.263,NaN

PPMXL                  0
RAJ2000[deg]           0
DEJ2000[deg]           0
pmRA[mas/yr]           0
pmDE[mas/yr]           0
e_pmRA[mas/yr]         0
e_pmDE[mas/yr]         0
Jmag[mag]              0
e_Jmag[mag]            0
Kmag[mag]              0
e_Kmag[mag]       484988
dtype: int64

It seems there is only one column **e_Kmag[mag]** containing actually NaN, and the rest of them contain empty cells. Let's replace empty cells by NaN and the drop them:

In [32]:
df = df.replace(
 
    r'^\s*$',
    np.nan,
    regex=True
)

In [33]:
display(df.sample(10, random_state=53))
display(df.isnull().sum())

,PPMXL,RAJ2000[deg],DEJ2000[deg],pmRA[mas/yr],pmDE[mas/yr],e_pmRA[mas/yr],e_pmDE[mas/yr],Jmag[mag],e_Jmag[mag],Kmag[mag],e_Kmag[mag]
638622,509580000000000000,54.557817,51.613627,-7.1,-8.8,6.6,6.6,16.944,0.215,15.785,NaN
140283,407390000000000000,46.561895,49.287592,17.9,-73.6,9.0,9.0,NaN,NaN,NaN,NaN
100879,409085000000000000,48.172238,50.135233,5.9,-0.1,4.8,4.8,15.932,0.075,15.606,0.191
473751,509754000000000000,54.667395,51.096806,-55.4,30.4,9.3,9.3,NaN,NaN,NaN,NaN
712472,509683000000000000,54.894513,51.911001,34.3,16.1,5.4,5.4,15.117,0.046,14.267,0.067
865557,413722000000000000,53.935258,47.232658,1.9,5.4,9.3,9.3,NaN,NaN,NaN,NaN
222993,509416000000000000,54.827487,50.386294,-5.0,-7.7,5.0,5.0,16.573,0.13,15.717,NaN
930302,412028000000000000,52.219179,46.674993,3.3,-11.0,5.7,5.7,NaN,NaN,NaN,NaN
932967,505782000000000000,50.868438,53.074816,-3.9,-1.2,5.1,5.1,16.373,0.129,15.742,NaN
62283,412216000000000000,49.879609,49.531914,-2.8,-4.7,4.2,4.2,14.874,0.039,14.401,0.071

PPMXL                  0
RAJ2000[deg]           0
DEJ2000[deg]           0
pmRA[mas/yr]           0
pmDE[mas/yr]           0
e_pmRA[mas/yr]         0
e_pmDE[mas/yr]         0
Jmag[mag]         419424
e_Jmag[mag]       423781
Kmag[mag]         419424
e_Kmag[mag]       484988
dtype: int64

Second, we drop all rows containing NaN:

In [34]:
display(f"Number of rows before dropping null values: {len(df)}")
df = df.dropna()
display(f"Number of rows after dropping null values: {len(df)}")

'Number of rows before dropping null values: 936329'

'Number of rows after dropping null values: 448891'