# Star Cluster Catalog Analysis with Pandas

- PPMXL ----------------------------------> star/source ID
  
- RAJ2000[deg] ---------------------------> Right Ascension in degrees
  
- DEJ2000[deg] ---------------------------> Declination in degrees
  
- pmRA[mas/yr] --------------------------> proper motion in RA
  
- pmDE[mas/yr] --------------------------> proper motion in De
  
- e_pmRA[mas/yr] -----------------------> error in proper motion RA
  
- e_pmDE[mas/yr] -----------------------> error in proper motion Dec
  
- Jmag[mag] -------------------------------> J-band infrared magnitude
  
- e_Jmag[mag] ----------------------------> error in J magnitude
  
- Kmag[mag] ------------------------------> K-band infrared magnitude
  
- e_Kmag[mag] ---------------------------> error in K magnitude

In [2]:
import pandas as pd
import numpy as np

* The original .xlsx file is around 65 MB. Run the code below to read .csv file and get rid of all metadata and other unnecessary data in original .xlsx file:

In [3]:
df= pd.read_csv('vizier_votable_catalog.csv') # Enter /data/sample.csv if you want to use the sample dataset instead of the full one.

Just to take a grasp of dataset:

In [4]:
display(df.head())

,PPMXL,RAJ2000[deg],DEJ2000[deg],pmRA[mas/yr],pmDE[mas/yr],e_pmRA[mas/yr],e_pmDE[mas/yr],Jmag[mag],e_Jmag[mag],Kmag[mag],e_Kmag[mag]
0,407349000000000000,45.959256,49.962081,17.6,1.9,6.3,6.3,16.713,0.146,15.928,NaN
1,407352000000000000,45.959337,49.891708,-5.3,0.6,5.5,5.5,,,,NaN
2,407349000000000000,45.959650,49.898794,-2.9,0.7,4.8,4.8,16.899,0.167,15.7,0.196
3,407350000000000000,45.959841,49.992809,0.4,2.9,5.5,5.5,,,,NaN
4,407349000000000000,45.960393,49.909459,-4.9,4.0,4.8,4.8,16.7,0.129,15.693,0.201

And to have more information about our dataset:

In [5]:
display(df.describe())
display(df.info())

,PPMXL,RAJ2000[deg],DEJ2000[deg],pmRA[mas/yr],pmDE[mas/yr],e_pmRA[mas/yr],e_pmDE[mas/yr],e_Kmag[mag]
count,9.363290e+05,936329.000000,936329.000000,936329.000000,936329.000000,936329.000000,936329.000000,451341.000000
mean,4.385381e+17,51.163103,49.860171,-2.302923,-3.426207,6.021949,6.023579,0.111040
std,4.349696e+16,2.515901,1.641183,56.174083,74.676329,2.503662,2.504908,0.075859
min,4.069950e+17,45.958814,46.561318,-8283.200000,-7681.700000,0.200000,0.200000,0.000000
25%,4.105920e+17,49.173383,48.526469,-5.000000,-7.300000,4.300000,4.300000,0.050000
50%,4.127500e+17,51.139387,49.852997,-1.000000,-2.500000,5.600000,5.600000,0.102000
75%,5.058270e+17,53.180827,51.211242,3.400000,1.600000,7.200000,7.200000,0.163000
max,5.106180e+17,56.203615,53.160317,7784.300000,8136.700000,50.000000,50.000000,9.998000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 936329 entries, 0 to 936328
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PPMXL           936329 non-null  int64
 1   RAJ2000[deg]    936329 non-null  float64
 2   DEJ2000[deg]    936329 non-null  float64
 3   pmRA[mas/yr]    936329 non-null  float64
 4   pmDE[mas/yr]    936329 non-null  float64
 5   e_pmRA[mas/yr]  936329 non-null  float64
 6   e_pmDE[mas/yr]  936329 non-null  float64
 7   Jmag[mag]       936329 non-null  object
 8   e_Jmag[mag]     936329 non-null  object
 9   Kmag[mag]       936329 non-null  object
 10  e_Kmag[mag]     451341 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 78.6+ MB

None

We have around 9 hundred thousand stars, in total 19 million information distributed in 11 columns :

In [10]:
display(df.size)
display(df.shape)

10299619

(936329, 11)