# Star Cluster Catalog Analysis with Pandas

- PPMXL ----------------------------------> star/source ID
  
- RAJ2000[deg] ---------------------------> Right Ascension in degrees
  
- DEJ2000[deg] ---------------------------> Declination in degrees
  
- pmRA[mas/yr] --------------------------> proper motion in RA
  
- pmDE[mas/yr] --------------------------> proper motion in De
  
- e_pmRA[mas/yr] -----------------------> error in proper motion RA
  
- e_pmDE[mas/yr] -----------------------> error in proper motion Dec
  
- Jmag[mag] -------------------------------> J-band infrared magnitude
  
- e_Jmag[mag] ----------------------------> error in J magnitude
  
- Kmag[mag] ------------------------------> K-band infrared magnitude
  
- e_Kmag[mag] ---------------------------> error in K magnitude

In [120]:
import pandas as pd
import numpy as np

* The original .xlsx file is around 65 MB. Run the code below to read .csv file and get rid of all metadata and other unnecessary data in original .xlsx file:

In [121]:
df= pd.read_csv('vizier_votable_catalog.csv') # Enter /data/sample.csv if you want to use the sample dataset instead of the full one.

Just to take a grasp of dataset:

In [122]:
display(df.head())

,PPMXL,RAJ2000[deg],DEJ2000[deg],pmRA[mas/yr],pmDE[mas/yr],e_pmRA[mas/yr],e_pmDE[mas/yr],Jmag[mag],e_Jmag[mag],Kmag[mag],e_Kmag[mag]
0,407349000000000000,45.959256,49.962081,17.6,1.9,6.3,6.3,16.713,0.146,15.928,NaN
1,407352000000000000,45.959337,49.891708,-5.3,0.6,5.5,5.5,,,,NaN
2,407349000000000000,45.959650,49.898794,-2.9,0.7,4.8,4.8,16.899,0.167,15.7,0.196
3,407350000000000000,45.959841,49.992809,0.4,2.9,5.5,5.5,,,,NaN
4,407349000000000000,45.960393,49.909459,-4.9,4.0,4.8,4.8,16.7,0.129,15.693,0.201

And to have more information about our dataset:

In [123]:
display(df.describe())
display(df.info())

,PPMXL,RAJ2000[deg],DEJ2000[deg],pmRA[mas/yr],pmDE[mas/yr],e_pmRA[mas/yr],e_pmDE[mas/yr],e_Kmag[mag]
count,9.363290e+05,936329.000000,936329.000000,936329.000000,936329.000000,936329.000000,936329.000000,451341.000000
mean,4.385381e+17,51.163103,49.860171,-2.302923,-3.426207,6.021949,6.023579,0.111040
std,4.349696e+16,2.515901,1.641183,56.174083,74.676329,2.503662,2.504908,0.075859
min,4.069950e+17,45.958814,46.561318,-8283.200000,-7681.700000,0.200000,0.200000,0.000000
25%,4.105920e+17,49.173383,48.526469,-5.000000,-7.300000,4.300000,4.300000,0.050000
50%,4.127500e+17,51.139387,49.852997,-1.000000,-2.500000,5.600000,5.600000,0.102000
75%,5.058270e+17,53.180827,51.211242,3.400000,1.600000,7.200000,7.200000,0.163000
max,5.106180e+17,56.203615,53.160317,7784.300000,8136.700000,50.000000,50.000000,9.998000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 936329 entries, 0 to 936328
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PPMXL           936329 non-null  int64
 1   RAJ2000[deg]    936329 non-null  float64
 2   DEJ2000[deg]    936329 non-null  float64
 3   pmRA[mas/yr]    936329 non-null  float64
 4   pmDE[mas/yr]    936329 non-null  float64
 5   e_pmRA[mas/yr]  936329 non-null  float64
 6   e_pmDE[mas/yr]  936329 non-null  float64
 7   Jmag[mag]       936329 non-null  object
 8   e_Jmag[mag]     936329 non-null  object
 9   Kmag[mag]       936329 non-null  object
 10  e_Kmag[mag]     451341 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 78.6+ MB

None

We have around 9 hundred thousand stars, in total 19 million information distributed in 11 columns :

In [124]:
display(df.size)
display(df.shape)

10299619

(936329, 11)

## Drop NaN
First of all, let's see how many NaN values we have among all elements and then drop them. 
    - first count the NaN

In [125]:
display(df.sample(10))
display(df.isnull().sum())

,PPMXL,RAJ2000[deg],DEJ2000[deg],pmRA[mas/yr],pmDE[mas/yr],e_pmRA[mas/yr],e_pmDE[mas/yr],Jmag[mag],e_Jmag[mag],Kmag[mag],e_Kmag[mag]
923154,506434000000000000,53.006107,52.752457,1.7,0.9,5.1,5.1,16.316,0.114,15.906,0.203
473517,509752000000000000,54.605815,51.128573,-6.5,-4.9,4.2,4.2,15.401,0.051,14.597,0.098
526860,409553000000000000,48.513498,51.400681,5.6,2.9,6.5,6.5,16.411,0.109,15.703,0.217
393262,509385000000000000,54.550493,50.807266,-145.9,-3.1,7.4,7.4,,,,NaN
846853,411201000000000000,49.614787,47.137318,0.4,0.0,9.3,9.3,,,,NaN
592487,414051000000000000,53.661928,48.145415,39.4,6.4,7.4,7.4,,,,NaN
221710,509409000000000000,54.525584,50.408686,0.2,6.1,4.8,4.8,16.403,0.122,15.425,0.188
338084,412602000000000000,51.644503,48.922446,9.1,-36.0,7.4,7.4,,,,NaN
645043,410271000000000000,47.735061,47.955195,-4.3,6.1,6.9,6.9,,,,NaN
237016,410609000000000000,48.312476,49.149673,3.2,-2.9,4.5,4.5,16.62,0.133,15.297,NaN

PPMXL                  0
RAJ2000[deg]           0
DEJ2000[deg]           0
pmRA[mas/yr]           0
pmDE[mas/yr]           0
e_pmRA[mas/yr]         0
e_pmDE[mas/yr]         0
Jmag[mag]              0
e_Jmag[mag]            0
Kmag[mag]              0
e_Kmag[mag]       484988
dtype: int64

It seems there is only one column **e_Kmag[mag]** containing actually NaN, and the rest of them contain empty cells. Let's replace empty cells by NaN and the drop them:

In [126]:
df = df.replace(
 
    r'^\s*$',
    np.nan,
    regex=True
)

In [127]:
display(df.sample(10, random_state=53))
display(df.isnull().sum())

,PPMXL,RAJ2000[deg],DEJ2000[deg],pmRA[mas/yr],pmDE[mas/yr],e_pmRA[mas/yr],e_pmDE[mas/yr],Jmag[mag],e_Jmag[mag],Kmag[mag],e_Kmag[mag]
638622,509580000000000000,54.557817,51.613627,-7.1,-8.8,6.6,6.6,16.944,0.215,15.785,NaN
140283,407390000000000000,46.561895,49.287592,17.9,-73.6,9.0,9.0,NaN,NaN,NaN,NaN
100879,409085000000000000,48.172238,50.135233,5.9,-0.1,4.8,4.8,15.932,0.075,15.606,0.191
473751,509754000000000000,54.667395,51.096806,-55.4,30.4,9.3,9.3,NaN,NaN,NaN,NaN
712472,509683000000000000,54.894513,51.911001,34.3,16.1,5.4,5.4,15.117,0.046,14.267,0.067
865557,413722000000000000,53.935258,47.232658,1.9,5.4,9.3,9.3,NaN,NaN,NaN,NaN
222993,509416000000000000,54.827487,50.386294,-5.0,-7.7,5.0,5.0,16.573,0.13,15.717,NaN
930302,412028000000000000,52.219179,46.674993,3.3,-11.0,5.7,5.7,NaN,NaN,NaN,NaN
932967,505782000000000000,50.868438,53.074816,-3.9,-1.2,5.1,5.1,16.373,0.129,15.742,NaN
62283,412216000000000000,49.879609,49.531914,-2.8,-4.7,4.2,4.2,14.874,0.039,14.401,0.071

PPMXL                  0
RAJ2000[deg]           0
DEJ2000[deg]           0
pmRA[mas/yr]           0
pmDE[mas/yr]           0
e_pmRA[mas/yr]         0
e_pmDE[mas/yr]         0
Jmag[mag]         419424
e_Jmag[mag]       423781
Kmag[mag]         419424
e_Kmag[mag]       484988
dtype: int64

Second, we drop all rows containing NaN:

In [128]:
display(f"Number of rows before dropping null values: {len(df)}")
df_cleaned = df.dropna()
display(f"Number of rows after dropping null values: {len(df_cleaned)}")

'Number of rows before dropping null values: 936329'

'Number of rows after dropping null values: 448891'

Now we find the rows for which Jmag > 15.5, display their total number and then drop them:
But before we get into that, let's check if any element of column Jmag is anything other than number. To do that, we convert all column to number. If it is already a number, it won't change, otherwise, if it is a string or anything else, it will change to NaN:

In [129]:
df_cleaned.loc[:, 'Jmag[mag]'] = pd.to_numeric(df_cleaned['Jmag[mag]'], errors='coerce')

display(df_cleaned['Jmag[mag]'].isna().sum())

0

The code above assures us that all element of column **Jmag** is a valid number, so:

In [130]:
df_cleaned_Jmag_deleted = df_cleaned[df_cleaned['Jmag[mag]'] > 15.5]
display(f"Number of rows to be deleted based on Jmag[mag] > 15.5: {len(df_cleaned_Jmag_deleted)}")

df_cleaned_Jmag = df_cleaned[df_cleaned['Jmag[mag]'] <= 15.5]   
display(f"Number of rows after filtering Jmag[mag] <= 15.5: {len(df_cleaned_Jmag)}")

display(f'Is it equal to the initial number of rows? {len(df_cleaned_Jmag) + len(df_cleaned_Jmag_deleted)==len(df_cleaned)}')

'Number of rows to be deleted based on Jmag[mag] > 15.5: 234577'

'Number of rows after filtering Jmag[mag] <= 15.5: 214314'

'Is it equal to the initial number of rows? True'

Next we filter our dataset based on Kmag <= 15.4:

In [131]:
df_cleaned_Jmag.loc[:, 'Kmag[mag]'] = pd.to_numeric(df_cleaned_Jmag['Kmag[mag]'], errors='coerce')

df_cleaned_Kmag_deleted = df_cleaned_Jmag[df_cleaned_Jmag['Kmag[mag]'] > 15.4]
display(f"Number of rows to be deleted based on Kmag[mag] > 15.4: {len(df_cleaned_Kmag_deleted)}")

df_cleaned_Kmag = df_cleaned_Jmag[df_cleaned_Jmag['Kmag[mag]'] <= 15.4]   
display(f"Number of rows after filtering Kmag[mag] <= 15.4: {len(df_cleaned_Kmag)}")

display(f'Is it equal to the initial number of rows? {len(df_cleaned_Kmag) + len(df_cleaned_Kmag_deleted)==len(df_cleaned_Jmag)}')

'Number of rows to be deleted based on Kmag[mag] > 15.4: 27'

'Number of rows after filtering Kmag[mag] <= 15.4: 214287'

'Is it equal to the initial number of rows? True'

Now we demand the error in proper motion (in Radian, e_pmRA) to be restricted between 4 and 10:

In [132]:
df_cleaned_Kmag.loc[:, 'e_pmRA[mas/yr]'] = pd.to_numeric(df_cleaned_Kmag['e_pmRA[mas/yr]'], errors='coerce')

df_cleaned_e_pmRA_deleted = df_cleaned_Kmag[(df_cleaned_Kmag['e_pmRA[mas/yr]'] > 10) | (df_cleaned_Kmag['e_pmRA[mas/yr]'] < 4)]
display(f"Number of rows to be deleted based on e_pmRA[mas/yr] > 10 or e_pmRA[mas/yr] < 4: {len(df_cleaned_e_pmRA_deleted)}")

df_cleaned_e_pmRA = df_cleaned_Kmag[(df_cleaned_Kmag['e_pmRA[mas/yr]'] <= 10) & (df_cleaned_Kmag['e_pmRA[mas/yr]'] >= 4)]
display(f"Number of rows after filtering e_pmRA[mas/yr] <= 10 and e_pmRA[mas/yr] >= 4: {len(df_cleaned_e_pmRA)}")

display(f'Is it equal to the initial number of rows? {len(df_cleaned_e_pmRA) + len(df_cleaned_e_pmRA_deleted)==len(df_cleaned_Kmag)}')

'Number of rows to be deleted based on e_pmRA[mas/yr] > 10 or e_pmRA[mas/yr] < 4: 13035'

'Number of rows after filtering e_pmRA[mas/yr] <= 10 and e_pmRA[mas/yr] >= 4: 201252'

'Is it equal to the initial number of rows? True'

Now this time, we demand the error in proper motion (in Degree, e_pmDE) to be restricted between 4 and 10:

In [133]:
df_cleaned_e_pmRA.loc[:, 'e_pmDE[mas/yr]'] = pd.to_numeric(df_cleaned_e_pmRA['e_pmDE[mas/yr]'], errors='coerce')

df_processed_data_deleted = df_cleaned_e_pmRA[(df_cleaned_e_pmRA['e_pmDE[mas/yr]'] > 10) | (df_cleaned_e_pmRA['e_pmDE[mas/yr]'] < 4)]
display(f"Number of rows to be deleted based on e_pmDE[mas/yr] > 10 or e_pmDE[mas/yr] < 4: {len(df_processed_data_deleted)}")

df_processed_data = df_cleaned_e_pmRA[(df_cleaned_e_pmRA['e_pmDE[mas/yr]'] <= 10) & (df_cleaned_e_pmRA['e_pmDE[mas/yr]'] >= 4)]
display(f"Number of rows after filtering e_pmDE[mas/yr] <= 10 and e_pmDE[mas/yr] >= 4: {len(df_processed_data)}")

display(f'Is it equal to the initial number of rows? {len(df_processed_data) + len(df_processed_data_deleted)==len(df_cleaned_e_pmRA)}')

'Number of rows to be deleted based on e_pmDE[mas/yr] > 10 or e_pmDE[mas/yr] < 4: 57'

'Number of rows after filtering e_pmDE[mas/yr] <= 10 and e_pmDE[mas/yr] >= 4: 201195'

'Is it equal to the initial number of rows? True'

Now we add another column, χ-squared (chi-squared), based on the correct columns:
(We copy df_processed_data to processed_data to avoid **SettingWithCopyWarning**)

In [134]:
processed_data = df_processed_data.copy()

RA_c = 52.5
Dec_c = 49.0
d_c = 172.4

mu_ac = 22.73
mu_dc = -26.51
e_ac = 0.17
e_dc = 0.17

s_ac0 = 0.7
s_dc0 = 0.7

s_ac1 = s_ac0/(d_c*4.74*10**(-3))
s_dc1 = s_dc0/(d_c*4.74*10**(-3))

processed_data.loc[:,'Chi_squared'] = (
        ((processed_data['pmRA[mas/yr]'] - mu_ac) ** 2) /
        ((processed_data['e_pmRA[mas/yr]'] ** 2) + e_ac ** 2 + s_ac1 ** 2) +
        ((processed_data['pmDE[mas/yr]'] - mu_dc) ** 2) /
        ((processed_data['e_pmDE[mas/yr]'] ** 2) + e_dc ** 2 + s_dc1 ** 2)
)

Now that we have created a new column, we have to filter χ-squared and eliminate χ-squared >= 6.17

In [135]:

final_processed_data_deleted = processed_data[processed_data['Chi_squared'] >= 6.17]
display(f"Number of rows to be deleted based on Chi_squared >= 6.17: {len(final_processed_data_deleted)}")

final_processed_data = processed_data[processed_data['Chi_squared'] < 6.17]
display(f"Number of rows after filtering Chi_squared < 6.17: {len(final_processed_data)}")

display(f'Is it equal to the initial number of rows? {len(final_processed_data) + len(final_processed_data_deleted)==len(processed_data)}')

'Number of rows to be deleted based on Chi_squared >= 6.17: 198730'

'Number of rows after filtering Chi_squared < 6.17: 2465'

'Is it equal to the initial number of rows? True'

Just the last check to make sure our filter is working fine:

In [136]:
display(final_processed_data.loc[
    (final_processed_data['Chi_squared'] >= 6.17) | 
    (final_processed_data['e_pmDE[mas/yr]'] > 10) | 
    (final_processed_data['e_pmDE[mas/yr]'] < 4)  |
    (final_processed_data['e_pmRA[mas/yr]'] > 10) | 
    (final_processed_data['e_pmRA[mas/yr]'] < 4)  |
    (df_cleaned_Jmag['Kmag[mag]'] > 15.4)         |
    (df_cleaned['Jmag[mag]'] > 15.5)
    ])

Empty DataFrame
Columns: [PPMXL, RAJ2000[deg], DEJ2000[deg], pmRA[mas/yr], pmDE[mas/yr], e_pmRA[mas/yr], e_pmDE[mas/yr], Jmag[mag], e_Jmag[mag], Kmag[mag], e_Kmag[mag], Chi_squared]
Index: []

Nothing!
Good!
Now is time to export result and move on to the next step to plot the result:

In [137]:
final_processed_data.to_csv('final_processed_data.csv', index=False)